<?php
/**
 * Reports Generate API Endpoint
 * Generates a report of the specified type and returns data/URL
 * 
 * Endpoint: GET /api/reports/generate.php?type=beneficiaries|attendance|stock|volunteers|donations
 * Auth: Bearer token required
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Access-Control-Allow-Credentials: true');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit(); }
if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed']);
    exit();
}

require_once __DIR__ . '/../../app/helpers/bootstrap.php';
require_once __DIR__ . '/../middleware/AuthMiddleware.php';

try {
    $db = getDBConnection();
    $auth = new AuthMiddleware($db);
    $user = $auth->requireAuth();

    $type = $_GET['type'] ?? '';

    if (!in_array($type, ['beneficiaries', 'attendance', 'stock', 'volunteers', 'donations'])) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Invalid report type']);
        exit();
    }

    $data = [];
    $reportName = '';

    if ($db !== null) {
        switch ($type) {
            case 'beneficiaries':
                $reportName = 'Beneficiary Report';
                $stmt = $db->query(
                    "SELECT BeneficiaryID, CONCAT(FirstName, ' ', LastName) AS FullName, 
                            Age, Gender, Phone, RegistrationDate, Status,
                            CASE WHEN Age < 18 THEN 'Child' WHEN Age >= 60 THEN 'Elderly' ELSE 'Adult' END AS Category
                     FROM Beneficiaries ORDER BY LastName, FirstName"
                );
                $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
                break;

            case 'attendance':
                $reportName = 'Attendance Report';
                $stmt = $db->query(
                    "SELECT a.SessionDate AS date, COUNT(*) AS registered,
                            SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) AS present,
                            ROUND(SUM(CASE WHEN a.Status = 'present' THEN 1 ELSE 0 END) / COUNT(*) * 100) AS rate
                     FROM Attendance a
                     WHERE a.SessionDate >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)
                     GROUP BY a.SessionDate ORDER BY a.SessionDate DESC"
                );
                $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
                break;

            case 'stock':
                $reportName = 'Stock Report';
                $stmt = $db->query(
                    "SELECT fs.ItemName, fs.Quantity, fs.Unit, fs.ExpiryDate,
                            COALESCE(SUM(fd.QuantityDistributed), 0) AS distributed,
                            CASE WHEN fs.Quantity <= 25 THEN 'Low' WHEN fs.Quantity <= 50 THEN 'Medium' ELSE 'Good' END AS stock_status
                     FROM FoodStock fs
                     LEFT JOIN FoodDistribution fd ON fs.FoodStockID = fd.FoodStockID
                     GROUP BY fs.FoodStockID ORDER BY fs.ItemName"
                );
                $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
                break;

            case 'volunteers':
                $reportName = 'Volunteer Report';
                $stmt = $db->query(
                    "SELECT u.FullName, u.Phone, u.Email, v.Skills, v.AvailabilityStatus, v.Status,
                            COUNT(vs.ScheduleID) AS total_shifts,
                            COALESCE(SUM(vs.HoursWorked), 0) AS total_hours
                     FROM Volunteers v
                     JOIN Users u ON v.UserID = u.UserID
                     LEFT JOIN VolunteerSchedules vs ON v.VolunteerID = vs.VolunteerID
                     GROUP BY v.VolunteerID ORDER BY u.FullName"
                );
                $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
                break;

            case 'donations':
                $reportName = 'Donations Report';
                $stmt = $db->query(
                    "SELECT DonorName, DonationType AS type, 
                            CASE WHEN DonationType = 'cash' THEN CONCAT('R', FORMAT(Amount, 2)) ELSE Description END AS item,
                            DonationDate AS date, Status, Amount
                     FROM Donations
                     WHERE DonationDate >= DATE_SUB(CURDATE(), INTERVAL 90 DAY)
                     ORDER BY DonationDate DESC"
                );
                $data = $stmt->fetchAll(PDO::FETCH_ASSOC);
                break;
        }
    }

    logMessage("Report '{$reportName}' generated by user '{$user['username']}'", 'INFO');

    echo json_encode([
        'success' => true,
        'message' => "{$reportName} generated",
        'data' => $data,
        'type' => $type,
        'count' => count($data)
    ]);

} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Internal server error']);
    logMessage("Reports generate error: " . $e->getMessage(), 'ERROR');
}